# Generated by Django 2.2.3 on 2020-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_smart_redis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcache',
            name='content_type',
            field=models.TextField(default='', verbose_name='Content Type'),
            preserve_default=False,
        ),
    ]
